<?php
// config/data.php
// Veritabanı (MySQL) bağlantısı olmadan, sistemi tamamen veritabanından bağımsız çalıştırmak için kullanılan statik veri kaynağıdır.

global $linux_distros;

$linux_distros = [
    [
        'id' => 1,
        'name' => 'Ubuntu',
        'slug' => 'ubuntu',
        'short_desc' => 'Son kullanıcılar için en popüler ve kullanımı en kolay dağıtımlardan biri.',
        'full_desc' => 'Debian tabanlı olup Canonical tarafından geliştirilmektedir. Aradığınız her türlü yazılım ve çözümü çok rahat bir şekilde topluluk forumlarında bulabilirsiniz. Yeni başlayan pclerde sıklıkla tercih edilir.',
        'base_os' => 'Debian',
        'package_manager' => 'APT / Snap',
        'difficulty' => 'Beginner',
        'desktop_environment' => 'GNOME',
        'ram_usage' => '1.5GB - 2GB',
        'developer' => 'Canonical Ltd.',
        'founder' => 'Mark Shuttleworth',
        'origin' => 'Güney Afrika / İngiltere',
        'founded' => '2004',
        'website' => 'https://ubuntu.com',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '24.04 LTS (Noble Numbat)',
        'philosophy' => 'Ubuntu, "insanlık" anlamına gelen bir Afrika felsefesidir. Herkes için ücretsiz, erişilebilir ve kullanımı kolay bir işletim sistemi sunmayı hedefler.',
        'fun_fact' => 'Her sürüm alfabetik sırayla bir hayvan adı alır. Canonical kurucusu Mark Shuttleworth, uzaya çıkan ilk Afrikalıdır.',
        'score_beginner' => 10,
        'score_gaming' => 8,
        'score_dev' => 9,
        'score_server' => 8,
        'score_old_pc' => 4,
        'score_security' => 6
    ],
    [
        'id' => 2,
        'name' => 'Linux Mint',
        'slug' => 'linux-mint',
        'short_desc' => 'Windows kullanıcıları için geçiş yapması en kolay, konforlu dağıtım.',
        'full_desc' => 'Windows benzeri arayüzü (Cinnamon/Mate), kurulu gelen medya codecleri ve sağlam Debian/Ubuntu tabanı ile acemilerin gözdesidir.',
        'base_os' => 'Ubuntu',
        'package_manager' => 'APT',
        'difficulty' => 'Beginner',
        'desktop_environment' => 'Cinnamon / MATE / XFCE',
        'ram_usage' => '1GB - 1.5GB',
        'developer' => 'Linux Mint Topluluğu',
        'founder' => 'Clément Lefèbvre',
        'origin' => 'İrlanda',
        'founded' => '2006',
        'website' => 'https://linuxmint.com',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '22 (Wilma)',
        'philosophy' => 'Kullanıcı deneyimini ön plana koyar. Windows\'dan geçiş yapanların hiç yabancılık çekmeden Linux kullanabilmesini hedefler.',
        'fun_fact' => 'Linux Mint, kendi masaüstü ortamı olan Cinnamon\'ı geliştirmiştir. Dünya genelinde en çok tercih edilen masaüstü Linux dağıtımlarından biridir.',
        'score_beginner' => 10,
        'score_gaming' => 7,
        'score_dev' => 8,
        'score_server' => 3,
        'score_old_pc' => 7,
        'score_security' => 5
    ],
    [
        'id' => 3,
        'name' => 'Debian',
        'slug' => 'debian',
        'short_desc' => 'Stabilite ve özgür yazılım deyince akla gelen ana kaya (rock solid) işletim sistemi.',
        'full_desc' => 'Birçok sistemin anasıdır (Ubuntu da dahil). Eski ama inanılmaz dengeli paketler kullanır. Sunucular için mükemmeldir, ancak masaüstünde yeni sürümler için sabır gerektirir.',
        'base_os' => 'Independent',
        'package_manager' => 'APT',
        'difficulty' => 'Intermediate',
        'desktop_environment' => 'GNOME / KDE / XFCE',
        'ram_usage' => '500MB - 1GB',
        'developer' => 'Debian Projesi (Gönüllü Topluluk)',
        'founder' => 'Ian Murdock',
        'origin' => 'ABD (Küresel topluluk)',
        'founded' => '1993',
        'website' => 'https://www.debian.org',
        'license' => 'DFSG (Debian Özgür Yazılım Yönergeleri)',
        'latest_version' => '12 (Bookworm)',
        'philosophy' => 'Tamamen özgür yazılıma bağlıdır. Kararlılık ve güvenilirlik her şeyin önündedir. "Evrensel İşletim Sistemi" mottosuyla bilinir.',
        'fun_fact' => 'Adını kurucusu Ian ve eşi Debra\'nın isimlerinin birleşiminden alır. Ubuntu, Knoppix, MX Linux gibi yüzlerce dağıtımın temelidir.',
        'score_beginner' => 5,
        'score_gaming' => 5,
        'score_dev' => 8,
        'score_server' => 10,
        'score_old_pc' => 6,
        'score_security' => 8
    ],
    [
        'id' => 4,
        'name' => 'Arch Linux',
        'slug' => 'arch-linux',
        'short_desc' => 'Kişiselleştirmenin ve kontrolün zirvesi. Sadece komut satırı ile kurulur.',
        'full_desc' => 'Rolling release mantığı ile her yazılımın anında en son sürümünü alırsınız. Ancak sistemi kırma riskiniz de sizin sorumluluğunuzdadır. "I use Arch btw" mottosunun sahibi.',
        'base_os' => 'Independent',
        'package_manager' => 'Pacman',
        'difficulty' => 'Advanced',
        'desktop_environment' => 'Tümü (Kullanıcı seçer)',
        'ram_usage' => 'Sisteme Göre Değişir',
        'developer' => 'Arch Linux Topluluğu',
        'founder' => 'Judd Vinet',
        'origin' => 'Kanada',
        'founded' => '2002',
        'website' => 'https://archlinux.org',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => 'Rolling Release (Sürekli güncelleme)',
        'philosophy' => 'KISS prensibi: Keep It Simple, Stupid. Sadeleşme ve kullanıcıya tam kontrol verme. Hiçbir şey otomatik yapılmaz, her şey kullanıcının elindedir.',
        'fun_fact' => '"I use Arch btw" ("Bu arada Arch kullanıyorum") internet meme\'i Linux topluluğunun en ünlü şakalarından biridir. Arch Wiki, dünyanın en kapsamlı Linux dokümantasyonudur.',
        'score_beginner' => 1,
        'score_gaming' => 9,
        'score_dev' => 10,
        'score_server' => 5,
        'score_old_pc' => 8,
        'score_security' => 7
    ],
    [
        'id' => 5,
        'name' => 'Kali Linux',
        'slug' => 'kali-linux',
        'short_desc' => 'Siber güvenlik, penetrasyon testleri ve hacking için geliştirilmiş devasa araç kutusu.',
        'full_desc' => 'Debian tabanlı olan Kali, günlük kullanım için tasarlanmamıştır. Root yetkisiyle işlemler yapılır, üzerinde binlerce siber güvenlik aracı barındırır.',
        'base_os' => 'Debian',
        'package_manager' => 'APT',
        'difficulty' => 'Advanced',
        'desktop_environment' => 'XFCE',
        'ram_usage' => '1GB - 1.5GB',
        'developer' => 'Offensive Security',
        'founder' => 'Mati Aharoni & Devon Kearns',
        'origin' => 'ABD',
        'founded' => '2013 (BackTrack\'in devamı, BackTrack: 2006)',
        'website' => 'https://www.kali.org',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '2024.3',
        'philosophy' => 'Siber güvenlik uzmanlarına ihtiyaç duydukları tüm araçları tek bir platformda sunmak. Penetrasyon testleri ve güvenlik denetimi için özel tasarlanmıştır.',
        'fun_fact' => 'Kali\'nin öncülü BackTrack, "Mr. Robot" dizisinde kullanılan işletim sistemiydi. 600\'den fazla siber güvenlik aracı önyüklü gelir.',
        'score_beginner' => 1,
        'score_gaming' => 2,
        'score_dev' => 8,
        'score_server' => 2,
        'score_old_pc' => 5,
        'score_security' => 10
    ],
    [
        'id' => 6,
        'name' => 'Fedora',
        'slug' => 'fedora',
        'short_desc' => 'Yenilikçi, temiz ve açık kaynak felsefesine sıkı sıkıya bağlı modern masaüstü.',
        'full_desc' => 'Red Hat tarafından desteklenir. Yeni kernel sürümleri ve güncel yazılımları çok kararlı bir şekilde son kullanıcıyla ilk buluşturan (Arch kadar ekstrem olmadan) dağıtımdır. Yazılımcılar çok sever.',
        'base_os' => 'Independent',
        'package_manager' => 'DNF',
        'difficulty' => 'Intermediate',
        'desktop_environment' => 'GNOME / KDE / vs.',
        'ram_usage' => '1.2GB - 2GB',
        'developer' => 'Fedora Projesi (Red Hat sponsorluğunda)',
        'founder' => 'Red Hat Inc. & Warren Togami',
        'origin' => 'ABD (Raleigh, North Carolina)',
        'founded' => '2003',
        'website' => 'https://fedoraproject.org',
        'license' => 'GPL (Tamamen özgür yazılım)',
        'latest_version' => '41',
        'philosophy' => 'İnovasyonu ilk benimseyen, açık kaynak felsefesine sıkı sıkıya bağlı bir topluluk dağıtımıdır. Red Hat Enterprise Linux\'un teknoloji inkübatörüdür.',
        'fun_fact' => 'Linux çekirdeğinin yaratıcısı Linus Torvalds, kişisel bilgisayarında Fedora kullanır. Fedora\'nın adı Red Hat logosundaki şapkadan gelir.',
        'score_beginner' => 6,
        'score_gaming' => 7,
        'score_dev' => 10,
        'score_server' => 7,
        'score_old_pc' => 4,
        'score_security' => 8
    ],
    [
        'id' => 7,
        'name' => 'Pop!_OS',
        'slug' => 'pop-os',
        'short_desc' => 'Nvidia sürücülerinin direkt entegre geldiği, oyun ve üretkenlik için popüler sistem.',
        'full_desc' => 'System76 tarafından geliştirilir. Ubuntu tabanlıdır ancak pencereleri döşeme (tiling) mantığı gibi özelliklerle harika bir iş akışı sunar.',
        'base_os' => 'Ubuntu',
        'package_manager' => 'APT / Flatpak',
        'difficulty' => 'Beginner',
        'desktop_environment' => 'COSMIC (GNOME tabanlı)',
        'ram_usage' => '1.5GB - 2GB',
        'developer' => 'System76',
        'founder' => 'Carl Richell (System76 CEO)',
        'origin' => 'ABD (Denver, Colorado)',
        'founded' => '2017',
        'website' => 'https://pop.system76.com',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '22.04 LTS',
        'philosophy' => 'Yaratıcılar, geliştiriciler ve bilim insanları için optimize edilmiş bir deneyim. Nvidia GPU kullanıcılarına özel ilk gün desteği.',
        'fun_fact' => 'System76 kendi Linux bilgisayarlarını üreten bir donanım şirketidir. Yeni nesil COSMIC masaüstü ortamını Rust programlama diliyle sıfırdan yazıyorlar.',
        'score_beginner' => 9,
        'score_gaming' => 10,
        'score_dev' => 9,
        'score_server' => 3,
        'score_old_pc' => 4,
        'score_security' => 6
    ],
    [
        'id' => 8,
        'name' => 'Lubuntu',
        'slug' => 'lubuntu',
        'short_desc' => 'Eski bilgisayarları tekrar canlandırmak için LXQt tabanlı aşırı hafif dağıtım.',
        'full_desc' => 'Eski laptoplar ve zayıf donanımlar için özel tasarlanmıştır. Sistem boştayken çok düşük RAM tüketir.',
        'base_os' => 'Ubuntu',
        'package_manager' => 'APT',
        'difficulty' => 'Beginner',
        'desktop_environment' => 'LXQt',
        'ram_usage' => '300MB - 500MB',
        'developer' => 'Lubuntu Topluluğu (Canonical destekli)',
        'founder' => 'Mario Behling',
        'origin' => 'Küresel Topluluk',
        'founded' => '2008',
        'website' => 'https://lubuntu.me',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '24.04 LTS',
        'philosophy' => 'Eski ve düşük kaynaklı bilgisayarları modern ve kullanılabilir hale getirmek. Hafiflik ve hız her şeyin önündedir.',
        'fun_fact' => 'Lubuntu, sadece 512MB RAM ile bile rahatça çalışabilir. Eski bilgisayarları çöpe atmak yerine Lubuntu yükleyerek yeniden hayata döndürebilirsiniz.',
        'score_beginner' => 9,
        'score_gaming' => 3,
        'score_dev' => 5,
        'score_server' => 2,
        'score_old_pc' => 10,
        'score_security' => 5
    ],
    [
        'id' => 9,
        'name' => 'Manjaro',
        'slug' => 'manjaro',
        'short_desc' => 'Arch Linux un zorluklarından arındırılmış, son kullanıcıya hazır Arch deneyimi.',
        'full_desc' => 'Arayüzü ve kurulumu kolaydır. Pacman ve AUR desteği sayesinde dünyadaki hemen hemen tüm programlara saniyeler içinde erişebilirsiniz.',
        'base_os' => 'Arch Linux',
        'package_manager' => 'Pacman',
        'difficulty' => 'Intermediate',
        'desktop_environment' => 'XFCE / KDE / GNOME',
        'ram_usage' => '1GB - 1.5GB',
        'developer' => 'Manjaro GmbH & Co. KG',
        'founder' => 'Philip Müller & Roland Singer',
        'origin' => 'Almanya / Avusturya',
        'founded' => '2011',
        'website' => 'https://manjaro.org',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '24.1 (Xahea)',
        'philosophy' => 'Arch Linux\'un gücünü, son kullanıcı için kolay ve erişilebilir hale getirmek. Rolling release ama stabil bir denge.',
        'fun_fact' => 'Manjaro, Arch paketlerini iki hafta geciktirerek alır ve kendi test süreçlerinden geçirir. Bu sayede rolling release\'in risklerini minimize eder.',
        'score_beginner' => 7,
        'score_gaming' => 9,
        'score_dev' => 8,
        'score_server' => 3,
        'score_old_pc' => 5,
        'score_security' => 6
    ],
    [
        'id' => 10,
        'name' => 'Zorin OS',
        'slug' => 'zorin-os',
        'short_desc' => 'Windows ve macOS kullanıcılarının Linux\'a en kolay ve görsel olarak en pürüzsüz geçiş yapması için tasarlanmış estetik sistem.',
        'full_desc' => 'Zorin OS, Windows kullanıcılarının yabancılık çekmemesi için özel olarak tasarlanmış harika bir "Görünüm Değiştirici" ile gelir. Tek tıklamayla Windows 11 veya macOS arayüzüne geçebilirsiniz. Cihazınızda çok şık durur. Ubuntu tabanlı olduğu için çok stabil çalışır ve Windows (.exe) uygulamalarını (WINE aracılığıyla) destekleyici araçları kutudan çıkar çıkmaz barındırır.',
        'base_os' => 'Ubuntu',
        'package_manager' => 'APT / Flatpak',
        'difficulty' => 'Beginner',
        'desktop_environment' => 'GNOME (Zorin Desktop)',
        'ram_usage' => '1.5GB - 2GB',
        'developer' => 'Zorin Group',
        'founder' => 'Artyom Zorin & Kyrill Zorin',
        'origin' => 'İrlanda (Dublin)',
        'founded' => '2009',
        'website' => 'https://zorin.com',
        'license' => 'GPL (Özgür Yazılım)',
        'latest_version' => '17.2',
        'philosophy' => 'Linux\'u herkes için erişilebilir kılmak. Windows ve macOS\'tan geçiş yapanların kendilerini evlerinde hissetmelerini sağlamak.',
        'fun_fact' => 'Zorin OS\'u kuran iki kardeş (Artyom ve Kyrill Zorin) projeye başladığında henüz lise öğrencisiydi. Bugün dünya genelinde milyonlarca kullanıcıya ulaştılar.',
        'score_beginner' => 10,
        'score_gaming' => 7,
        'score_dev' => 7,
        'score_server' => 2,
        'score_old_pc' => 6,
        'score_security' => 4
    ]
];

// Helper fonk: Slug'dan distro bulma
function getDistroBySlug($slug) {
    global $linux_distros;
    foreach($linux_distros as $d) {
        if($d['slug'] === $slug) {
            return $d;
        }
    }
    return null;
}
?>
